// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxoibrkfagadvygdhqsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94b2licmtmYWdhZHZ5Z2RocXN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NzE3NzgsImV4cCI6MjA3NDU0Nzc3OH0.DCRLUVTxl9aXTaBZK7xg_Iy_TzF53uEbooiJRJvGqBc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});